server:
  port: 40100

logging:
  level:
    org.springframework: debug
    com.neusoft.mapper: debug

spring:
  application:
    name: virtualwallet-server
  datasource:
    username: root
    password: dyq73028
    url: jdbc:mysql://localhost:3306/elm?characterEncoding=utf-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.neusoft.po

